language: go
matrix:
  include:
    - go: 1.x
      env: LATEST=true
    - go: 1.14.x
    - go: 1.13.x
    - go: tip
  allow_failures:
    - go: tip

install:
  - export GO111MODULE=on
  - go get -t -v $(go list ./... | grep -v -E "vendor|go_fatal_error|robotn|shirou|go_robot")
  - go test -test.v -bench="." $(go list ./... | grep -v -E "vendor|go_fatal_error|robotn|shirou|go_robot" | grep "demojson")

script:
  - export GO111MODULE=on
  - go test -cover -coverprofile=coverage.txt -covermode=atomic -v $(go list ./... | grep -v -E "vendor|go_fatal_error|robotn|shirou|go_robot")

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email: false