language: go
matrix:
  include:
    - go: 1.x
      env: LATEST=true
    - go: 1.13.x
    - go: tip
  allow_failures:
    - go: tip

install:
  - export GO111MODULE=on
  - go get -t -v $(go list ./... | grep -v -E "vendor|go_fatal_error")

script:
  - GO111MODULE=on
  - go test -cover -coverprofile=coverage.txt -covermode=atomic -v $(go list ./... | grep -v -E "vendor|go_fatal_error")

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email: false