language: go
matrix:
  include:
    - go: 1.x
      env: LATEST=true
    - go: 1.14.x
    - go: 1.13.x
    - go: tip
  allow_failures:
    - go: tip

install:
  - make travisTest
  - make travisBenchmem

script:
  - GO111MODULE=on
  - make travisConvey

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email: false